### ISSUE TITLE
No-copy bitmap creation on existing memory area

### ISSUE THREAD

**Issue by maciej** [RoaringBitmap/roaring#116]
It should be possible to create a `roaring.Bitmap` from a memory buffer (a `byte[]`) containing a memory-mapped serialised Roaring Bitmap, if the [RoaringFormatSpec](https://github.com/RoaringBitmap/RoaringFormatSpec) was used. Unlike `Bitmap.ReadFrom(io.Reader)` it would not copy the input data.

I think the method might not be portable across every architecture / host system. It would use [reflect.SlideHeader](https://golang.org/pkg/reflect/#SliceHeader) to construct roaring data structures (mostly container data).

**Comment by lemire** [comment]
Yes. Our Java implementation allows this though the result is immutable.

**Comment by maciej** [comment]
I think it'd be safe if this method would also produce an immutable `roaring.Bitmap`. I'm hoping this would be achievable by using the current copy-on-write functionality.

**Comment by lemire** [comment]
That’s a good point.

**Comment by maciej** [comment]
I've started working on this one. The development branch is [here](https://github.com/maciej/roaring/commits/roaring-116).

**Comment by lemire** [comment]
Great news. It is valuable work.

**Comment by maciej** [comment]
Working on this I've noticed the memory format of serialised run containers is different to how run containers (`runContainer16`) are represented in this implementation.

For now I guess I'll resort to copying the and changing the length fields to "last" fields, but ideally I think we'd want `runContainer16` implementation to change.

One thing to remember is that this would likely break the _msgpack_ serialisation and will require custom serialisers. How big of a concern do you think is that? Will it be OK to incompatible or should we maintain compatibility here?

cc // @glycerine @lemire

**Comment by glycerine** [comment]
I implemented the `msgpack` serialization as a temporary stopgap before doing the roaring standard serialization since the roaring hadn't been fully spec-ed out yet; then later when Daniel fleshed out the spec we went back and did that; which is nice since it matches the other Roaring language bindings. So I don't think its a big deal to change the msgpack. But then I'm not using the msgpack presently either(!)  If you want to avoid back/forward compatibility issues and still use msgpack, you could adopt by `greenpack` instead (https://github.com/glycerine/greenpack) which provides protobuf like field version numbers. But mostly I'd recommend seeing if you can't drop the msgpack all together. It does have the nice property of being able to handle future extensions more easily, but its likely just extra baggage we don't need.  That's just my impression. If anyone is actually using the msgpack at the moment, they might feel differently.

**Comment by maciej** [comment]
@glycerine thanks for a getting back to me on that quickly!

I'd be also for dropping msgpack support altogether.

The native serialization format is much superior in terms of performance. In Java roaring implementation (I think the same is also true for C), you can create a roaring bitmap (`ImmutableRoaringBitmap` instance) without any memory copies. _mmap_ a file from disk and you have the bitmap ready. That's impossible to get with a format that requires any decoders, unmarshaller, etc…

**Comment by lemire** [comment]
We can document the break and, of course, increment the version accordingly.
