### ISSUE TITLE
How to split large bitmap to chunks of serializedSizeInBytes=4Kb? 

### ISSUE THREAD

**Issue by AskAlexSharov** [RoaringBitmap/roaring#272]

**Comment by lemire** [comment]
I am going to close this issue because it is too vague. I invite you to open a new issue with more details.

- If you think that there is a bug, don't please provide a detailed explanation.
- If you'd want to propose a new feature, please describe fully the feature and/or propose a pull request.

If you have questions about Roaring bitmaps, please make sure you first read our published work... e.g., 
* Samy Chambi, Daniel Lemire, Owen Kaser, Robert Godin,  [Better bitmap performance with Roaring bitmaps](https://arxiv.org/abs/1402.6407), Software: Practice and Experience 46 (5), 2016
