### ISSUE TITLE
Sorry for asking but...

### ISSUE THREAD

**Issue by gitmko0** [RoaringBitmap/roaring#275]
What's the size of 2^64 roaring bitmap?
I'm trying to use roaring bitmap to store ipv6 blacklist information.

was wondering if it's better to just stick to "normal" byte information storage for ipv6 or using roaring bitmap?

maybe 200M ipv6 blacklist information that's all.

will it be better using roaring bitmap? basically, what's the byte size requirement for this? and when will we know when roaring bitmap is not a good fit for a scenario other than actually running it? is there like a ... gauge we can guesstimate whether it is worth implementation at scale?

**Comment by lemire** [comment]
I would not use a single Roaring bitmap as a filter. It would be the wrong data structure in most cases. You typically  use roaring bitmaps to represent many sets that interact in non-trivial manners.

> maybe 200M ipv6 blacklist information that's all.

Have you considered using something like an XOR filter? You could have a 225MB filter that is super fast.

https://github.com/FastFilter/xorfilter

With a probabilistic filter, you still need to handle the fall back, but that becomes much easier since the fall back is no longer performance critical.



> What's the size of 2^64 roaring bitmap?

For N= 2^64, the [0,N) universe is large, effectively infinite, compared to any data set. In such an interval, we can rely on information theory. Given a set of values taken at random from the universe, what information theory tells you is that no storage technique can ever do better than log(N) bits... or 64 bits. That's the best that any technique can do, and all of them will have some overhead.

There is really no reason to use roaring bitmaps if your data is effectively made of random values. If it is non-random, then the answer depends on your data distribution. If you provide your data distribution, then we can tell you the storage requirement.

**Comment by gitmko0** [comment]
great answer! thanks.

**Comment by gitmko0** [comment]
i checked xorfilter, i beg to differ. i think roaring is a better filter because of the compression offered than the xorfilter.
200M blacklist information being roaring bitmapped... if xorfilter is compressed, that'll make it more suitable then.

can you give a reason not to use roaring as a filter? coz to me, it's mem efficient.

(out of topic) makes me wonder if there is a xor / bloom filter that's compressed.

**Comment by lemire** [comment]
Please insert your data into both the `xorfilter` and into `roaring` and report back.

If you get unexpected results, people open a new issue, detailing your experiences, with hard numbers.

**Comment by lemire** [comment]
(typo above, I meant to write "please open a new issue with hard numbers.")
