### ISSUE TITLE
Panic from Contains

### ISSUE THREAD

**Issue by elgatito** [RoaringBitmap/roaring#278]
Hello,

I'm creating a new bitmap with:
`awaitingPieces = roaring.NewBitmap()`

Then checking if there are items in there with:
`awaitingPieces.ContainsInt(curPiece)`

It works fine, but sometimes I get these panics:
```
panic: runtime error: index out of range [0] with length 0

goroutine 1055349 [running]:
github.com/RoaringBitmap/roaring.(*roaringArray).getContainer(0x480e380, 0x2a360000, 0xbdf4, 0x18f9340)
 	/go/pkg/mod/github.com/!roaring!bitmap/roaring@v0.4.23/roaringarray.go:307 +0x94
github.com/RoaringBitmap/roaring.(*Bitmap).Contains(0x480e380, 0x27c, 0x537f818)
 	/go/pkg/mod/github.com/!roaring!bitmap/roaring@v0.4.23/roaring.go:490 +0x30
github.com/RoaringBitmap/roaring.(*Bitmap).ContainsInt(...)
 	/go/pkg/mod/github.com/!roaring!bitmap/roaring@v0.4.23/roaring.go:496
```

Can't reproduce it since there are tons of checks. but panic comes rarely and I cannot find the reason.

**Comment by lemire** [comment]
As you are no doubt aware, this code as been in production in large systems worldwide. We do have bugs still, but your first instinct given an issue should be to assume that the bug is in your code.

> Can't reproduce it since there are tons of checks. but panic comes rarely and I cannot find the reason.


It likely that your code is multithreaded (e.g., you might be using goroutines). If so, then you are responsible for safety: i.e., it is not is generally safe to creat a bitmap in a thread and then access it in another thread. To have safety, you need to add the necessary precautions. It is entirely on you as a programmer to guard your code.


I am going to close this since it is impossible for us to verify the issue given the current description.

Please reopen with a failing test. Ideally, your failing test should be single-threaded (e.g., no goroutine).

Please be mindful that if you cannot verify the issue, we are not likely to be able to do so. We need as much information as possible.

**Comment by elgatito** [comment]
@lemire Ouch, have not seen this notification:

```
Goroutine safety
In general, it should not generally be considered safe to access the same bitmaps using different goroutines--they are left unsynchronized for performance. Should you want to access a Bitmap from more than one goroutine, you should provide synchronization. Typically this is done by using channels to pass the *Bitmap around (in Go style; so there is only ever one owner), or by using sync.Mutex to serialize operations on Bitmaps.
```

You are right, have no locks around bitset uses, so probably just got a case with that.
Thanks for this great package!
