### ISSUE TITLE
When the quantity is less than 4096, the container is an arrayContainer. Is there any way to force it to be converted to a bitmapContainer

### ISSUE THREAD

**Issue by xq182** [RoaringBitmap/roaring#448]
When the quantity is less than 4096, the container is an arrayContainer. Is there any way to force it to be converted to a bitmapContainer

**Comment by xq182** [comment]
Is there any difference in the retrieval efficiency of bitmapContainer and arrayContainer at a specific data size?

**Comment by lemire** [comment]
This issue is closed. If you are encountering performance issues with your application, please open a distinct issue. Please provide full details, including benchmarks. The community will be happy to discuss the issue you are encountering if it is well documented.

Note that I encourage you to read our documentation, and in particular to section related to whether Roaring bitmaps are well suited to your application.

You are reminded that if you disagree with the fundamental design decisions of Roaring bitmaps: it is open source... you can fork the project for your own specific needs, if you want.
